# Homework 3 - Xiao Li - 223009075

# Question 1

In [102]:
import numpy as np
x=np.zeros(10)
x[4]=1
x

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

# Question 2

In [103]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Question 3

In [104]:
def reverse(x):
    rev_x=x[::-1]
    return(rev_x)
arr1=[1,2,3,4,5]
arr2 =[4,2,666,3,2]
print(reverse(arr1))
print(reverse(arr2))

[5, 4, 3, 2, 1]
[2, 3, 666, 2, 4]


# Quesiton 4

In [105]:
def find_nonzero(x):
    idx = np.nonzero(x)[0]
    return(print(idx))
x=[1,2,0,0,4,0]
find_nonzero(x)

[0 1 4]


# Question 5

In [108]:
x = np.random.normal(0, 1, (3,3,3))
x

array([[[ 0.28922027, -0.23709449, -0.92345074],
        [ 0.55355643, -1.97565386, -1.09949707],
        [-0.00391783,  1.75769868, -0.39300736]],

       [[-0.91700803,  0.18289528, -0.53573173],
        [-0.2069522 ,  0.68751746,  0.11544765],
        [-0.54259041, -0.92319727, -0.91848743]],

       [[ 0.34203561,  0.29633535,  1.17162017],
        [-0.36707241, -0.66794175, -0.97574241],
        [-0.43340155, -1.58650458,  0.4337715 ]]])

# Question 6

In [113]:
x = np.random.rand(10, 10)
Sce_row=min(x[1,:])
Fourth_column=max(x[:,3])
print(Sce_row)
print(Fourth_column)
x

0.193096083328
0.970459891626


array([[ 0.97602203,  0.44698469,  0.05307794,  0.18830533,  0.87265877,
         0.64418488,  0.33557143,  0.04241705,  0.92984417,  0.83650382],
       [ 0.7617921 ,  0.74821822,  0.19309608,  0.3924628 ,  0.62957083,
         0.51199173,  0.63172645,  0.73315927,  0.69728937,  0.22841898],
       [ 0.51685062,  0.39923262,  0.04000317,  0.05769262,  0.09791722,
         0.56498204,  0.55679591,  0.34859701,  0.10222852,  0.8970077 ],
       [ 0.45352712,  0.1916114 ,  0.74295342,  0.03180861,  0.70960906,
         0.77651483,  0.79581296,  0.26350767,  0.43064171,  0.65112977],
       [ 0.65608475,  0.7061047 ,  0.10400383,  0.97045989,  0.25232742,
         0.0375676 ,  0.74216106,  0.52903173,  0.13365333,  0.00431724],
       [ 0.67324008,  0.23047704,  0.51925736,  0.02913004,  0.0587948 ,
         0.33513142,  0.47576862,  0.83840376,  0.87318177,  0.45350495],
       [ 0.32786385,  0.03247753,  0.96102741,  0.6209739 ,  0.66996259,
         0.16218927,  0.09529206,  0.6807494 

# Question 7

In [120]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


# Question 8

In [123]:
x = np.random.random(10)
x.sort()
x

array([ 0.01744063,  0.09590425,  0.09819709,  0.16751988,  0.2365803 ,
        0.5338225 ,  0.61393828,  0.70171571,  0.71551841,  0.97809443])

# Question 9

In [127]:
def is_equal(A,B):
    equal = np.array_equal(A, B)
    return(print(equal))

A = [1,2,4]
B = [1,2,4]
C = [1,2,4,7]
D = [1,3,4]
is_equal(A,B)
is_equal(A,C)
is_equal(A,D)


True
False
False


# Question 10

In [132]:
#creating a matrix
arr = np.array([[1., 2., 3.,], [4., 5., 6.], [7., 8., 9.]])
print(arr)
#calculating the mean for each row, and substract it from the respective row
arr - arr.mean(axis=1, keepdims=True) 

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

# Question 11

In [134]:
a = np.random.rand(5, 5, 3) 
b = np.random.rand(3, 5, 5) 
c = np.random.rand(5, 5)
#change the shape of c to (5,5,1) so as to multiply it with a whose shape is(5,5,3)
print(a*c[:,:,np.newaxis])
print(b*c)


[[[ 0.31324229  0.2183401   0.061633  ]
  [ 0.36649315  0.40496865  0.44136308]
  [ 0.51483002  0.68404362  0.6719523 ]
  [ 0.94554866  0.70914677  0.44593275]
  [ 0.68739523  0.32354533  0.95275618]]

 [[ 0.24295583  0.85960035  0.43377227]
  [ 0.43988376  0.59397127  0.44359474]
  [ 0.10754586  0.18150672  0.01004727]
  [ 0.20547085  0.46637254  0.11872118]
  [ 0.36666243  0.59268864  0.073608  ]]

 [[ 0.52271992  0.03617295  0.30074729]
  [ 0.38076435  0.06485617  0.36807802]
  [ 0.56666779  0.43398109  0.31593644]
  [ 0.41873723  0.60013966  0.05835889]
  [ 0.13681171  0.28646879  0.21172086]]

 [[ 0.06695894  0.49864777  0.30558432]
  [ 0.06750677  0.68672267  0.16791948]
  [ 0.16812833  0.13397464  0.23509669]
  [ 0.53854417  0.75751233  0.22750512]
  [ 0.23057166  0.20404742  0.2442804 ]]

 [[ 0.41329043  0.10226578  0.51199335]
  [ 0.50672743  0.77552378  0.62630443]
  [ 0.45117434  0.43550699  0.35566174]
  [ 0.01519561  0.02055431  0.01088747]
  [ 0.20268719  0.1888699   0.29

(5, 5, 1)

# Question 12

In [135]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R=[]
for i in Z:
    if i+3 > len(Z):
        break
    else:
        R.append(Z[i-1:i+3])
R

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10],
 [8, 9, 10, 11],
 [9, 10, 11, 12],
 [10, 11, 12, 13],
 [11, 12, 13, 14]]

# Question 13

In [140]:
#contracting a function to convert from Cartesian to polar coordinates
def cart2polar(x,y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)* 180 / np.pi
    return([rho, phi])
#contracting a 4x2 array of Cartesian coordinates
a = np.array([[1,1],[2,2],[1,1.732],[1.732,1]])
x=[]
for i in a:
    #calculating the polar coordinates and store into an array with the same shape.
    x.append(cart2polar(i[0],i[1]))
x


[[1.4142135623730951, 45.0],
 [2.8284271247461903, 45.0],
 [1.9999559995159892, 59.999272219172632],
 [1.9999559995159892, 30.000727780827372]]

# Question 14

In [143]:
import time
#start time of solution I
time1_start=time.time()
a = np.arange(1024.0).reshape(4, 8, 16, 2)  
b = np.random.rand(4, 8, 16, 2)             
sol = a * b 
#end time of solution I
time1_end=time.time()

#start time of solution II
time2_start=time.time()
#contructing an empty array with size(4*8*16*2)
sol2=np.empty([4,8,16,2])
for i in range (a.shape [0]): 
    for j in range (a.shape [1]): 
        for k in range (a.shape [2]): 
            for l in range (a.shape [3]): 
                 sol2[i, j, k, l]=a[i , j , k , l] * b [i , j, k, l]
#end time of solution II
time2_end=time.time()

#calculating the time that solution I takes
T1=time1_end-time1_start
#calculating the time that solution II takes
T2=time2_end-time2_start

#testing if these two solution get the same result
assert (sol==sol2).all()
print('Solution I takes {:6.10f} seconds.'.format(T1))
print('Solution II takes {:6.10f} seconds.'.format(T2))
print('Solution II takes {:6.10f} seconds longer than Solution I.'.format(T2-T1))
#keep two decimal places
print('Solution II takes {:6.4f} times longer than Solution I.'.format(T2/T1))


Solution I takes 0.0002951622 seconds.
Solution II takes 0.0017459393 seconds.
Solution II takes 0.0014507771 seconds longer than Solution I.
Solution II takes 5.9152 times longer than Solution I.


# Question 15

In [98]:
def calculate(a, b):
    """
    the code aa /= 4. has changed the original data of a
    here the code a[:2, :]-=a[:2, :]/4 is calculate the  1/4 of the [:2,:] elements first, then
    substract them from the elements themselves, then assign the values back to a
    """
    a[:2, :]-=a[:2, :]/4
    
    """
    a and b are with different shape (3,2) and (3), the codea*b[:,np.newaxis] can change the 
    shape of b to (3,1) which allows b to be able to multiply with a.
    """
    return a*b[:,np.newaxis]
    

a = np.ones((3, 2))
b = np.ones(3)*3

res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()
print(res)

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


# Question 16

In [159]:
import math
#contructing a funtion takes input(direction & speed)
def u_v(vdir,vspd):
    u=np.zeros(vdir.shape)
    v=np.zeros(vspd.shape)
    u=np.cos(vdir/180*np.pi)*vspd
    v=np.sin(vdir/180*np.pi)*vspd
    return u,v
# read in data
data = np.loadtxt('/Users/lixiao/python4geosciences/data/burl1h2010.txt', comments='#')
# select two columns (direction &speed) as input for using function
a=[]
a=u_v(data[:,5],data[:,6])
u=a[0]
v=a[1]
print(u)
print(v)




[ -2.08397511  -1.96070053  -2.12119911 ...,  -9.56084447 -10.50707636
  -8.83345912]
[ 2.1580194   3.01921404  2.52794666 ...,  6.208885    5.5867116   5.1       ]


# Question 17

In [245]:
import glob
#creating a class
class dataclass(object):
    
    def __init__(self, name, salt, temp):
        self.name = name
        self.salt = salt
        self.temp = temp
    #calculate the mean of salt
    def salt_mean(self):
        return np.mean(self.salt)
    #calculate the maximum of temp
    def temp_max(self):
        return max(self.temp)
#creating a new list wind to store classes
wind=[] 
#reading all files using loop
for i in glob.glob("/Users/lixiao/python4geosciences/data/MCH/*.cnv2"):
    f = open(i)
    a=f.readlines()
    salt=[]
    temp=[]
    #reading the file name
    name=i.split('/')[-1][:-5]
    for line in a[57:]:
        data = line.split()
        if not data: continue
        salt.append(float(data[5]))
        temp.append(float(data[2]))
    #organizing salt and temp as a class and add it into the lise wind
    wind.append(dataclass(name,salt,temp))
print(wind[2].name)
print(wind[2].temp)
wind[-1].salt_mean()



m1002a
[21.2128, 21.2149, 21.2177, 21.219, 21.2165, 21.2331, 21.3468, 21.4867, 21.526, 21.5914, 21.6244, 21.6219, 21.6295, 21.6204, 21.6003, 21.5912, 21.4888, 21.3504, 21.2779, 21.343, 21.4117, 21.4415, 21.441, 21.3959, 21.3208, 21.2352, 21.1793, 21.1591, 21.1479, 21.1501, 21.1435, 21.1413, 21.1385, 21.1377, 21.1369]


35.828874999999996

# Question 18

In [243]:
#Solution I: sliding window taking N elements from the right side of the point. 
#Then do the average. sum/(N+1) (point + N points)
#For the last few elements(<N), will keep the average of last N+1 elements
def Runningmean(x, N):
    y = np.zeros((len(x),))
    for i in range(len(x)):
        if N==0:
            return x
        if N>len(x):
            print ("The window size exceeds the data size")
            break
        if i+N < len(x):
            y[i] = np.sum(x[i:(i+N+1)])
        #the value of last N elements equal to their average value
        else:
            y[i] = np.sum(x[-(N+1):])
    return y/(N+1)
x=[2,3,4,5,6,7,8,9]
Runningmean(x,3)

array([ 3.5,  4.5,  5.5,  6.5,  7.5,  7.5,  7.5,  7.5])

In [244]:
#Solution II: sliding window taking N elements from both sides. 
#Then do the average sum/(2N+1) (N points from 2 sides + point)
#For the first few elements. We will take all the left elements(<N) and take N elements from
#the right side, Then calculate the average for them.
#For the last few elemets. We will take all the right elemets(<N) and take N elements from
#the left side, Then calculate the average for them.
def Runningmean(x, N):
    y = np.zeros((len(x),))
    for i in range(len(x)):
        if N==0:
            return x
        if N>len(x):
            print ("The window size exceeds the data size")
            break
        if i-N<0:
            y[i] = (np.sum(x[:i])+ np.sum(x[i:(i+N+1)]))/(i+N+1)
        elif i+N < len(x):
            y[i] = (np.sum(x[i:(i+N+1)])+ np.sum(x[(i-N):i]))/(2*N+1)
        elif i+N >=len(x):
            y[i] = (np.sum(x[i:])+ np.sum(x[(i-N):i]))/(len(x)-i+N)
    return y
x=[2,3,4,5,6,7,8,9]
Runningmean(x,3)

array([ 3.5,  4. ,  4.5,  5. ,  6. ,  6.5,  7. ,  7.5])